import CoreGraphics
import Foundation

// A trackpad touch independent of AppKit so the gesture logic can be tested.
struct TouchSample {
    enum Phase {
        case began
        case moved
        case stationary
        case ended
        case cancelled
    }

    let id: String
    let position: CGPoint
    let phase: Phase
    let isResting: Bool

    init(id: String, position: CGPoint, phase: Phase = .moved, isResting: Bool = false) {
        self.id = id
        self.position = position
        self.phase = phase
        self.isResting = isResting
    }

    var isActive: Bool {
        return phase != .ended && phase != .cancelled
    }
}

enum SwipeEvent: Equatable {
    case startOrContinue(Direction)
    case end

    enum Direction {
        case left
        case right
    }
}

// Turns a stream of trackpad touches into App Switcher gestures.
class GestureRecognizer {
    static let accVelXThreshold: Float = 0.07
    // TODO: figure out the real value of the delay.
    static let appSwitcherUIDelay: TimeInterval = 0.2

    var fingerCount: Int {
        didSet {
            if fingerCount != oldValue {
                touchesCount = 0
                clearEventState()
            }
        }
    }

    // Number of fingers currently touching the trackpad.
    private(set) var touchesCount = 0
    // Event state.
    private var accVelX: Float = 0
    private var prevTouchPositions: [String: CGPoint] = [:]
    // Gesture state. Gesture may consists of multiple events.
    private var startTime: TimeInterval? = nil
    // Set when a scroll sequence was blocked so its momentum is blocked as well.
    private var isBlockingScroll = false

    init(fingerCount: Int) {
        self.fingerCount = fingerCount
    }

    var isGestureActive: Bool {
        return startTime != nil
    }

    // Swiping with the gesture fingers must not scroll the content under the cursor.
    func shouldBlockScroll(isMomentum: Bool) -> Bool {
        if isMomentum {
            return isBlockingScroll
        }
        isBlockingScroll = touchesCount == fingerCount
        return isBlockingScroll
    }

    // Legacy swipe events (e.g. "Swipe between pages" with three fingers) are generated by the same fingers.
    var shouldBlockSwipe: Bool {
        return touchesCount == fingerCount
    }

    // Finishes the current gesture (if any) and forgets all the touches.
    func reset() -> SwipeEvent? {
        let event: SwipeEvent? = isGestureActive ? .end : nil
        startTime = nil
        touchesCount = 0
        isBlockingScroll = false
        clearEventState()
        return event
    }

    func process(touches allTouches: [TouchSample], time: TimeInterval) -> SwipeEvent? {
        // Resting touches (e.g. a thumb resting on the trackpad) are not a part of any gesture.
        let touches = allTouches.filter({ !$0.isResting })

        // Sometimes there are empty touch events that we have to skip. There are no empty touch events if Mission Control or App Expose use 3-finger swipes though.
        if touches.isEmpty {
            return nil
        }
        touchesCount = touches.filter({ $0.isActive }).count

        if touchesCount == fingerCount {
            return processGestureFingers(touches: touches, time: time)
        } else if touchesCount >= 2 && touchesCount < fingerCount {
            // Two fingers scrolling in App Switcher is OK but we shouldn't accumulate gesture velocity here.
            clearEventState()
            return nil
        } else {
            return processOtherFingers()
        }
    }

    private func processGestureFingers(touches: [TouchSample], time: TimeInterval) -> SwipeEvent? {
        // We don't care about non-horizontal swipes.
        guard let velX = horizontalSwipeVelocity(touches: touches) else {
            return nil
        }

        accVelX += velX
        // Not enough swiping.
        if abs(accVelX) < GestureRecognizer.accVelXThreshold {
            return nil
        }

        if let startTime = startTime {
            if time - startTime < GestureRecognizer.appSwitcherUIDelay {
                // We skip subsequent events until App Switcher UI is shown.
                clearEventState()
                return nil
            }
        } else {
            startTime = time
        }

        let direction: SwipeEvent.Direction = accVelX < 0 ? .left : .right
        clearEventState()
        return .startOrContinue(direction)
    }

    private func processOtherFingers() -> SwipeEvent? {
        let event: SwipeEvent? = isGestureActive ? .end : nil
        startTime = nil
        clearEventState()
        return event
    }

    private func clearEventState() {
        accVelX = 0
        prevTouchPositions.removeAll()
    }

    private func horizontalSwipeVelocity(touches: [TouchSample]) -> Float? {
        var allRight = true
        var allLeft = true
        var sumVelX = Float(0)
        var sumVelY = Float(0)
        for touch in touches {
            let (velX, velY) = touchVelocity(touch)
            allRight = allRight && velX >= 0
            allLeft = allLeft && velX <= 0
            sumVelX += velX
            sumVelY += velY

            if touch.isActive {
                prevTouchPositions[touch.id] = touch.position
            } else {
                prevTouchPositions.removeValue(forKey: touch.id)
            }
        }
        // All fingers should move in the same direction.
        if !allRight && !allLeft {
            return nil
        }

        let velX = sumVelX / Float(touches.count)
        let velY = sumVelY / Float(touches.count)
        // Only horizontal swipes are interesting.
        if abs(velX) <= abs(velY) {
            return nil
        }

        return velX
    }

    private func touchVelocity(_ touch: TouchSample) -> (Float, Float) {
        guard let prevPosition = prevTouchPositions[touch.id] else {
            return (0, 0)
        }
        let position = touch.position
        return (Float(position.x - prevPosition.x), Float(position.y - prevPosition.y))
    }
}
