import CoreGraphics
import Foundation

// A trackpad touch independent of AppKit so the gesture logic can be tested.
struct TouchSample {
    enum Phase {
        case began
        case moved
        case stationary
        case ended
        case cancelled
    }

    let id: String
    let position: CGPoint
    let phase: Phase
    let isResting: Bool

    init(id: String, position: CGPoint, phase: Phase = .moved, isResting: Bool = false) {
        self.id = id
        self.position = position
        self.phase = phase
        self.isResting = isResting
    }

    var isActive: Bool {
        return phase != .ended && phase != .cancelled
    }
}

enum ScrollPhase {
    // A mouse wheel or another device without phases.
    case none
    case mayBegin
    case began
    case changed
    case ended
    case cancelled
}

enum ScrollAction {
    case pass
    case block
    // The window under the cursor has already received the beginning of this scroll, so finish it instead of dropping it.
    case end
}

enum SwipeEvent: Equatable {
    case startOrContinue(Direction)
    case end

    enum Direction {
        case left
        case right
    }
}

// Turns a stream of trackpad touches into App Switcher gestures.
// Works like the 3-finger swipe on Windows: the first swipe opens App Switcher, then the selection follows the fingers
// (sliding right selects the next app, sliding back selects the previous one) and lifting the fingers switches to the selected app.
class GestureRecognizer {
    // Horizontal distance (in trackpad widths) that opens App Switcher.
    static let accVelXThreshold: Float = 0.07
    // Horizontal distance between two apps in App Switcher.
    static let stepDistance: Float = 0.12
    // How far the fingers have to slide back past a step before the selection goes back, so fingers resting on a step boundary don't flicker.
    static let hysteresis: Float = 0.04
    // TODO: figure out the real value of the delay.
    static let appSwitcherUIDelay: TimeInterval = 0.2

    var fingerCount: Int {
        didSet {
            if fingerCount != oldValue {
                touchesCount = 0
                clearEventState()
            }
        }
    }

    // Number of fingers currently touching the trackpad.
    private(set) var touchesCount = 0
    // Event state.
    private var accVelX: Float = 0
    private var prevTouchPositions: [String: CGPoint] = [:]
    // Gesture state. Gesture may consists of multiple events.
    private var startTime: TimeInterval? = nil
    // Horizontal distance the fingers moved since the gesture started.
    private var offset: Float = 0
    // Selected app relative to the current one: positive to the right, negative to the left.
    private var position = 0
    // Set after the gesture ended until all the fingers are lifted, so the remaining fingers neither scroll nor start a new gesture.
    private var isLiftingFingers = false
    // Set when a scroll sequence was blocked so its momentum is blocked as well.
    private var isBlockingScroll = false
    // Set while the window under the cursor is in the middle of a scroll sequence.
    private var isScrollSequenceDelivered = false

    init(fingerCount: Int) {
        self.fingerCount = fingerCount
    }

    var isGestureActive: Bool {
        return startTime != nil
    }

    // Swiping with the gesture fingers must not scroll the content under the cursor.
    func scrollAction(phase: ScrollPhase, isMomentum: Bool, time: TimeInterval) -> ScrollAction {
        if isMomentum {
            return isBlockingScroll ? .block : .pass
        }
        isBlockingScroll = shouldBlockScroll(time: time)
        if isBlockingScroll {
            if isScrollSequenceDelivered {
                isScrollSequenceDelivered = false
                return .end
            }
            return .block
        }
        switch phase {
        case .mayBegin, .began, .changed:
            isScrollSequenceDelivered = true
        case .none, .ended, .cancelled:
            isScrollSequenceDelivered = false
        }
        return .pass
    }

    private func shouldBlockScroll(time: TimeInterval) -> Bool {
        if touchesCount == fingerCount || (isGestureActive && touchesCount > fingerCount) || isLiftingFingers {
            return true
        }
        // Command is held while the gesture is active. Until App Switcher UI is shown, scrolling would reach the window under the cursor as Command-scroll (e.g. zoom).
        if let startTime = startTime, time - startTime < GestureRecognizer.appSwitcherUIDelay {
            return true
        }
        return false
    }

    // Legacy swipe events (e.g. "Swipe between pages" with three fingers) are generated by the same fingers.
    var shouldBlockSwipe: Bool {
        return touchesCount == fingerCount
    }

    // Finishes the current gesture (if any) and forgets all the touches.
    func reset() -> SwipeEvent? {
        let event: SwipeEvent? = isGestureActive ? .end : nil
        clearGestureState()
        touchesCount = 0
        isBlockingScroll = false
        isLiftingFingers = false
        clearEventState()
        return event
    }

    func process(touches allTouches: [TouchSample], time: TimeInterval) -> SwipeEvent? {
        // Sometimes there are empty touch events that we have to skip. There are no empty touch events if Mission Control or App Expose use 3-finger swipes though.
        if allTouches.isEmpty {
            return nil
        }
        // Resting touches (e.g. a thumb resting on the trackpad) are not a part of any gesture.
        // Only resting touches left means the gesture fingers are gone, so the gesture ends and Command is never left pressed.
        let touches = allTouches.filter({ !$0.isResting })
        touchesCount = touches.filter({ $0.isActive }).count

        if isLiftingFingers {
            if touchesCount == 0 {
                isLiftingFingers = false
            }
            clearEventState()
            return nil
        }

        if touchesCount == fingerCount {
            return processGestureFingers(touches: touches, time: time)
        } else if touchesCount > fingerCount && isGestureActive {
            // A palm or another finger brushing the trackpad mid-swipe must not end the gesture.
            clearEventState()
            return nil
        } else {
            return processOtherFingers()
        }
    }

    private func processGestureFingers(touches: [TouchSample], time: TimeInterval) -> SwipeEvent? {
        let (velX, isHorizontalSwipe) = swipeVelocity(touches: touches)

        if !isGestureActive {
            // We don't care about non-horizontal swipes.
            if !isHorizontalSwipe {
                return nil
            }
            accVelX += velX
            // Not enough swiping.
            if abs(accVelX) < GestureRecognizer.accVelXThreshold {
                return nil
            }
            startTime = time
            offset = accVelX
            position = accVelX < 0 ? -1 : 1
            return .startOrContinue(accVelX < 0 ? .left : .right)
        }

        // The selection follows the fingers.
        offset += velX
        let rightEdge = position >= 0 ? GestureRecognizer.boundary(position + 1) : GestureRecognizer.boundary(position) + GestureRecognizer.hysteresis
        let leftEdge = position <= 0 ? GestureRecognizer.boundary(position - 1) : GestureRecognizer.boundary(position) - GestureRecognizer.hysteresis
        if offset >= rightEdge {
            position += 1
            return .startOrContinue(.right)
        }
        if offset <= leftEdge {
            position -= 1
            return .startOrContinue(.left)
        }
        return nil
    }

    // Offset where the selection moves onto the given step (non-zero) from the step next to it towards the current app.
    private static func boundary(_ step: Int) -> Float {
        let distance = accVelXThreshold + Float(abs(step) - 1) * stepDistance
        return step > 0 ? distance : -distance
    }

    private func processOtherFingers() -> SwipeEvent? {
        let event: SwipeEvent? = isGestureActive ? .end : nil
        // Lifting the fingers selects the app. The fingers rarely leave the trackpad at the same time, so wait for all of them.
        isLiftingFingers = isGestureActive && touchesCount > 0
        clearGestureState()
        clearEventState()
        return event
    }

    private func clearGestureState() {
        startTime = nil
        offset = 0
        position = 0
    }

    private func clearEventState() {
        accVelX = 0
        prevTouchPositions.removeAll()
    }

    // Average horizontal velocity of the fingers and whether they swipe horizontally in the same direction.
    private func swipeVelocity(touches: [TouchSample]) -> (Float, Bool) {
        var allRight = true
        var allLeft = true
        var sumVelX = Float(0)
        var sumVelY = Float(0)
        for touch in touches {
            let (velX, velY) = touchVelocity(touch)
            allRight = allRight && velX >= 0
            allLeft = allLeft && velX <= 0
            sumVelX += velX
            sumVelY += velY

            if touch.isActive {
                prevTouchPositions[touch.id] = touch.position
            } else {
                prevTouchPositions.removeValue(forKey: touch.id)
            }
        }
        let velX = sumVelX / Float(touches.count)
        let velY = sumVelY / Float(touches.count)
        // All fingers should move in the same direction and only horizontal swipes are interesting.
        let isHorizontalSwipe = (allRight || allLeft) && abs(velX) > abs(velY)
        return (velX, isHorizontalSwipe)
    }

    private func touchVelocity(_ touch: TouchSample) -> (Float, Float) {
        guard let prevPosition = prevTouchPositions[touch.id] else {
            return (0, 0)
        }
        let position = touch.position
        return (Float(position.x - prevPosition.x), Float(position.y - prevPosition.y))
    }
}
