import Cocoa

class SwipeManager {
    private static let accVelXThreshold: Float = 0.07
    // TODO: figure out the real value of the delay.
    private static let appSwitcherUIDelay: Double = 0.2

    private static let eventsOfInterest: CGEventMask =
        NSEvent.EventTypeMask.gesture.rawValue |
        NSEvent.EventTypeMask.scrollWheel.rawValue |
        NSEvent.EventTypeMask.swipe.rawValue

    private static var eventTap: CFMachPort? = nil
    private static var runLoopSource: CFRunLoopSource? = nil
    // Event state.
    private static var accVelX: Float = 0
    private static var prevTouchPositions: [String: NSPoint] = [:]
    // Gesture state. Gesture may consists of multiple events.
    private static var startTime: Date? = nil
    // Number of fingers currently touching the trackpad.
    private static var touchesCount = 0
    // Set when a scroll sequence was blocked so its momentum is blocked as well.
    private static var isBlockingScroll = false

    //TODO: move it somewhere else?
    private static func listener(_ eventType: EventType) {
        switch eventType {
        case .startOrContinue(.left):
            AppSwitcher.cmdShiftTab()
            performHapticFeedback()
        case .startOrContinue(.right):
            AppSwitcher.cmdTab()
            performHapticFeedback()
        case .end:
            AppSwitcher.selectInAppSwitcher()
        }
    }

    private static func performHapticFeedback() {
        if Settings.hapticFeedback {
            NSHapticFeedbackManager.defaultPerformer.perform(.alignment, performanceTime: .now)
        }
    }

    static var isRunning: Bool {
        return eventTap != nil
    }

    static func start() {
        if eventTap != nil {
            debugPrint("SwipeManager is already started")
            return
        }
        debugPrint("SwipeManager start")
        eventTap = CGEvent.tapCreate(
            tap: .cghidEventTap,
            place: .headInsertEventTap,
            options: .defaultTap,
            eventsOfInterest: eventsOfInterest,
            callback: { proxy, type, cgEvent, userInfo in
                return SwipeManager.eventHandler(proxy: proxy, eventType: type, cgEvent: cgEvent, userInfo: userInfo)
            },
            userInfo: nil
        )
        guard let eventTap = eventTap else {
            debugPrint("SwipeManager couldn't create event tap")
            return
        }

        runLoopSource = CFMachPortCreateRunLoopSource(nil, eventTap, 0)
        CFRunLoopAddSource(CFRunLoopGetMain(), runLoopSource, CFRunLoopMode.commonModes)
        CGEvent.tapEnable(tap: eventTap, enable: true)
    }

    static func stop() {
        reset()
        guard let tap = eventTap else {
            return
        }
        debugPrint("SwipeManager stop")
        CGEvent.tapEnable(tap: tap, enable: false)
        if let runLoopSource = runLoopSource {
            CFRunLoopRemoveSource(CFRunLoopGetMain(), runLoopSource, CFRunLoopMode.commonModes)
        }
        CFMachPortInvalidate(tap)
        runLoopSource = nil
        eventTap = nil
    }

    static func restart() {
        stop()
        start()
    }

    // The event tap may silently die after sleep, user switching or permission changes. Recreate or re-enable it if needed.
    static func ensureRunning() {
        guard let tap = eventTap, CFMachPortIsValid(tap) else {
            debugPrint("SwipeManager event tap is invalid, recreating")
            restart()
            return
        }
        if !CGEvent.tapIsEnabled(tap: tap) {
            debugPrint("SwipeManager event tap is disabled, enabling")
            CGEvent.tapEnable(tap: tap, enable: true)
            if !CGEvent.tapIsEnabled(tap: tap) {
                restart()
            }
        }
    }

    // Finishes the current gesture (if any) and forgets all the touches.
    static func reset() {
        if startTime != nil {
            endGesture()
        }
        startTime = nil
        touchesCount = 0
        isBlockingScroll = false
        clearEventState()
    }

    private static func eventHandler(proxy: CGEventTapProxy, eventType: CGEventType, cgEvent: CGEvent, userInfo: UnsafeMutableRawPointer?) -> Unmanaged<CGEvent>? {
        if eventType == .tapDisabledByUserInput || eventType == .tapDisabledByTimeout {
            debugPrint("SwipeManager tap disabled", eventType.rawValue)
            // Some touches may have been missed so start from scratch.
            reset()
            if let tap = eventTap {
                CGEvent.tapEnable(tap: tap, enable: true)
            }
            return Unmanaged.passUnretained(cgEvent)
        }

        if eventType == .scrollWheel {
            return shouldBlockScroll(cgEvent) ? nil : Unmanaged.passUnretained(cgEvent)
        }

        if eventType.rawValue == NSEvent.EventType.swipe.rawValue {
            // Legacy swipe events (e.g. "Swipe between pages" with three fingers) are generated by the same fingers.
            return touchesCount == Settings.fingerCount ? nil : Unmanaged.passUnretained(cgEvent)
        }

        if eventType.rawValue == NSEvent.EventType.gesture.rawValue, let nsEvent = NSEvent(cgEvent: cgEvent) {
            touchEventHandler(nsEvent)
        }
        return Unmanaged.passUnretained(cgEvent)
    }

    // Swiping with the gesture fingers must not scroll the content under the cursor.
    private static func shouldBlockScroll(_ cgEvent: CGEvent) -> Bool {
        let isMomentum = cgEvent.getIntegerValueField(.scrollWheelEventMomentumPhase) != 0
        if isMomentum {
            return isBlockingScroll
        }
        if touchesCount == Settings.fingerCount {
            isBlockingScroll = true
            return true
        }
        isBlockingScroll = false
        return false
    }

    private static func touchEventHandler(_ nsEvent: NSEvent) {
        // Resting touches (e.g. a thumb resting on the trackpad) are not a part of any gesture.
        let touches = nsEvent.allTouches().filter({ !$0.isResting })

        // Sometimes there are empty touch events that we have to skip. There are no empty touch events if Mission Control or App Expose use 3-finger swipes though.
        if touches.isEmpty {
            return
        }
        let activeTouches = touches.filter({ $0.phase != .ended && $0.phase != .cancelled })
        touchesCount = activeTouches.count

        let fingerCount = Settings.fingerCount
        if touchesCount == fingerCount {
            processGestureFingers(touches: touches)
        } else if touchesCount >= 2 && touchesCount < fingerCount {
            processScrollFingers()
        } else {
            processOtherFingers()
        }
    }

    private static func processScrollFingers() {
        // Two fingers scrolling in App Switcher is OK but we shouldn't accumulate gesture velocity here.
        clearEventState()
    }

    private static func processGestureFingers(touches: Set<NSTouch>) {
        // We don't care about non-horizontal swipes.
        guard let velX = SwipeManager.horizontalSwipeVelocity(touches: touches) else {
            return
        }

        accVelX += velX
        // Not enough swiping.
        if abs(accVelX) < accVelXThreshold {
            return
        }

        if let startTime = startTime {
            if -startTime.timeIntervalSinceNow < appSwitcherUIDelay {
                // We skip subsequent events until App Switcher UI is shown.
                clearEventState()
                return
            }
        } else {
            startTime = Date()
        }

        startOrContinueGesture()
        clearEventState()
    }

    private static func processOtherFingers() {
        if startTime != nil {
            endGesture()
            startTime = nil
        }
        clearEventState()
    }

    private static func clearEventState() {
        accVelX = 0
        prevTouchPositions.removeAll()
    }

    private static func startOrContinueGesture() {
        let direction: EventType.Direction = accVelX < 0 ? .left : .right
        listener(.startOrContinue(direction: direction))
    }

    private static func endGesture() {
        listener(.end)
    }

    private static func horizontalSwipeVelocity(touches: Set<NSTouch>) -> Float? {
        var allRight = true
        var allLeft = true
        var sumVelX = Float(0)
        var sumVelY = Float(0)
        for touch in touches {
            let (velX, velY) = touchVelocity(touch)
            allRight = allRight && velX >= 0
            allLeft = allLeft && velX <= 0
            sumVelX += velX
            sumVelY += velY

            if touch.phase == .ended || touch.phase == .cancelled {
                prevTouchPositions.removeValue(forKey: "\(touch.identity)")
            } else {
                prevTouchPositions["\(touch.identity)"] = touch.normalizedPosition
            }
        }
        // All fingers should move in the same direction.
        if !allRight && !allLeft {
            return nil
        }

        let velX = sumVelX / Float(touches.count)
        let velY = sumVelY / Float(touches.count)
        // Only horizontal swipes are interesting.
        if abs(velX) <= abs(velY) {
            return nil
        }

        return velX
    }

    private static func touchVelocity(_ touch: NSTouch) -> (Float, Float) {
        guard let prevPosition = prevTouchPositions["\(touch.identity)"] else {
            return (0, 0)
        }
        let position = touch.normalizedPosition
        return (Float(position.x - prevPosition.x), Float(position.y - prevPosition.y))
    }

    enum EventType {
        case startOrContinue(direction: Direction)
        case end

        enum Direction {
            case left
            case right
        }
    }
}
